### ISSUE TITLE
[BUG] https://cryptocointrader.be/ points at localhost:3000 to get list data

### ISSUE THREAD

**Issue by IAMtheIAM** [SockTrader/SockTrader#40] opened 2019-11-04 20:32 UTC
https://cryptocointrader.be/ - this doesn't load correctly See console error log:

```
localhost:3000/data/list:1 Failed to load resource: the server responded with a status of 404 (Not Found)
candles.ts:57 Error: Request failed with status code 404
    at e.exports (createError.js:17)
    at e.exports (settle.js:19)
    at XMLHttpRequest.d.onreadystatechange (xhr.js:60)
(anonymous) @ candles.ts:57
localhost:3000/strategy/list:1 Failed to load resource: the server responded with a status of 404 (Not Found)
```

Can you fix it so it doesn't point at localhost:3000 - it should point to the webserver host.

**Comment by cwouter** [comment] 2019-11-05 06:44
Hey @IAMtheIAM, this is by design. The frontend expects you to run SockTrader locally on Port 3000.

Steps to make things work:
1. Clone the project
2. Run ‘npm run web’

This script will start a local webserver. We’re thinking about to make the Port and host configurable in the frontend and add some user friendly warning messages. That would make it less confusing I guess.

**Comment by IAMtheIAM** [comment] 2019-11-07 17:03
Oh, that's not what I expected. I thought the hosted interface was designed so that new users could come test the project out without needing to clone anything. Is the dashboard UI part of the project, so we could run that locally as well?

**Comment by cwouter** [comment] 2019-11-07 18:00
I understand the confusion. Its something that we need to work on. And unfortunately we’re obligated to make the dashboard closed source. Otherwise we would violate the TOS of TradingView. (The library to render the charts)

**Comment by cwouter** [comment] 2019-11-10 11:40
I'll close this issue since it's not really a bug. And i'll create another one to improve the dashboard and notify new users about the usage of dashboard. #43

**Closed by cwouter** 2019-11-10 11:40 UTC
Labels: bug
